### ISSUE TITLE
Make distFolder optional

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#152]
### Issue Description

For basic sites that don't min, less, etc (i.e. don't make any files) we may not need a `distFolder`. If it's possible would be nice to have this as an optional parameter if possible.

**Comment by vincentmorneau** [comment]
So basically it would just trigger Browsersync on the srcFolder without any transformation. Interesting idea for those wanting a quick AFEB environment.

**Comment by vincentmorneau** [comment]
Effect: creates some sort of dependency between the distFolder and the options below as distFolder is needed for any transformation:

![image](https://cloud.githubusercontent.com/assets/5391291/21183884/02610a6a-c1d8-11e6-80d1-bee6c2703ad0.png)

A simple disable mechanism should be enough.

**Comment by martindsouza** [comment]
From a UI perspective you could have it that the Concatenation and other fields are greyed out (or hidden) until a value is entered into the Destination Folder.

**Comment by vincentmorneau** [comment]
I'm bumping this up, as it will be much easier with our new configuration module.
