### ISSUE TITLE
Review new app process mecanism

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-frontend-boost#171]
What if G_APP_IMAGES was an app substitution string and the app process was

```sql
declare
    l_cookie owa_cookie.cookie;
begin
    l_cookie := owa_cookie.get('oos-apex-frontend-boost-app-images');
    if l_cookie.vals.count > 0 then
        :G_APP_IMAGES := l_cookie.vals(1);
    -- else
    -- no else neede because G_APP_IMAGES is an App Substitution String
    --    :G_APP_IMAGES := :APP_IMAGES;
    end if;
end;
```

Need to review all cases but that would simplify the process...

**Comment by martindsouza** [comment]
See [`apex_plugin_util.replace_substitutions`](https://docs.oracle.com/cd/E59726_01/doc.50/e39149/apex_plugin_util.htm#AEAPI2289) which will help replace sub strings.

**Comment by vincentmorneau** [comment]
Is that needed here?

A test case was made so that G_APP_IMAGES was a substitution string instead of an application item.
Line 6 (`:G_APP_IMAGES := l_cookie.vals(1);`) replaces the value of that substitution string without the need of the API.

**Comment by vincentmorneau** [comment]
Closing this, as we realized we can't manipulate a substitution string like an item. Keeping original solution for now.
