### ISSUE TITLE
Look at integrating Webpack

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#179]
https://webpack.js.org

Would be good to only have people include one asset file in their application. 
Seems as though development community is moving away from Grunt and Gulp towards Webpack.

**Comment by vincentmorneau** [comment]
Originally going to integrate Browserify, but now it seems like Webpack is winning in popularity. 

Going to close https://github.com/OraOpenSource/apex-frontend-boost/issues/125

**Comment by vincentmorneau** [comment]
Bumping this to the next release

**Comment by vincentmorneau** [comment]
See https://github.com/shama/webpack-stream/issues/125#issuecomment-258600779 

I would rather use webpack directly than a gulp plugin.
