### ISSUE TITLE
"dist" folder cannot be managed with svn

### ISSUE THREAD

**Issue by rimblas** [OraOpenSource/apex-frontend-boost#183]
### Issue Description
svn creates a `.svn` directory on every managed directory of the repo.
If "dist" directory is under svn, afeb will wipe the contents, including the `.svn` directory and mess up the repository.

### APEX Front-End Boost Version
3.0.2

### Operating System
Mac OS X 10.11.16

### Node Version
v6.9.2

**Comment by vincentmorneau** [comment]
Solution was to update SVN. See: http://subversion.apache.org/docs/release-notes/1.7.html#single-db

> Instead of a .svn directory in every directory in the working copy, Subversion 1.7 working copies have just one .svn directory—in the root of the working copy.
