### ISSUE TITLE
Using static workspace files

### ISSUE THREAD

**Issue by dwarcake** [OraOpenSource/apex-frontend-boost#187]
### Issue Description
Enhancement:
Possibility to use the substitution #WORKSPACE_IMAGES#.
Since we can have multiple applications working with eachother ( one for authentication purpose, others for each module of the app ) it would be useful to work with "Workspace Static Files" instead of "Application Static Files".
The publisher could then also create the files there, since there is a different API call available.

### APEX Front-End Boost Version
APEX Front-End Boost version 3.0.2

### Operating System
Windows

### Node Version
v6.9.5

### Browser
56.0.2924.87 (Official Build) (32-bit)

### APEX Version
v5.0.4

**Comment by vincentmorneau** [comment]
That's a good point. There is also THEME_IMAGES which would be interesting to have. I'll have to review this. Thank you for taking the time to post the issue.

**Comment by dwarcake** [comment]
Got it working on my pc by modifying following code after installing.
This is just a hard-coded change and not adjustable per application.

Search for the following file (or something similar):
`C:\Users\<USER>\AppData\Roaming\npm\node_modules\apex-frontend-boost\lib\sqlcl\distUpload.js`

Search for comments "// inserts the file"
Replacing the code underneath with following:
```
" " + apexSchema + ".wwv_flow_api.create_workspace_static_file (" +
" p_file_name => l_file_name" +
" , p_mime_type => nvl(l_mime_type, 'application/octet-stream')" +
" , p_file_charset => 'utf-8'" +
" , p_file_content => :b" +
" );" +
" end;";
```

The "Application Process" in APEX should look like this:
```
declare
l_cookie owa_cookie.cookie;
begin
l_cookie := owa_cookie.get('oos-apex-frontend-boost-app-images');
if l_cookie.vals.count > 0 then
apex_application.G_COMPANY_IMAGES := l_cookie.vals(1);
end if;
end;
```

Might save you some time and help others that want to use #WORKSPACE_IMAGES# until it is implemented :-)

**Comment by vincentmorneau** [comment]
That is great, thank you for looking into it yourself.

I'll find a way to merge this.

**Comment by vincentmorneau** [comment]
Follow-up: need to add an additional setting in the AFEB configuration. Most probably in the "APEX" section.
