### ISSUE TITLE
Error when Theme roller item field is empty

### ISSUE THREAD

**Issue by dwarcake** [OraOpenSource/apex-frontend-boost#191]
When running afeb config <project> :
At the bottom of the config there's an option to "Add items" for "Theme roller".

I just upgraded to "APEX Front-End Boost version 3.1.3" and got following error on an existing project:
(node:1596) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid glob argument:

Has to do with a parameter being empty.
Removed the empty item at "Theme roller" section and the problem was solved.

Maybe possible to check if the field is not empty when saving the config ?

**Comment by vincentmorneau** [comment]
Absolutely, thanks for finding out! For now just don't add empty fields in there. It'll be fixed in the next release.
