### ISSUE TITLE
Not reload the "Page Designer" tab

### ISSUE THREAD

**Issue by dwarcake** [OraOpenSource/apex-frontend-boost#196]
### Issue Description
Currently when editing a JavaScript file, both the Page Designer and the application get refreshed when you don't have any unsaved changes.
The Page Designer doesn't benefit from this reload.
After the refresh you have to go to your DA / Page Item / Process again to continue what you were doing.

### APEX Front-End Boost Version
APEX Front-End Boost version 3.1.3

### Operating System
Windows

### APEX Version
[Example: v5.1.0]

Is there a possibility to only reload the tab / window with the application ?

**Comment by vincentmorneau** [comment]
Thank you for reporting this. It has bothered me for a long time too, but now that it bothers you too, I'll find a way to resolve it.

**Comment by vincentmorneau** [comment]
Well that was easier than I thought. Thanks again for pushing me into this issue.

**Comment by dwarcake** [comment]
Happy to help :-)
Using AFEB on a daily basis and on those days I have to edit quite a bit of JavaScript it bugs me, thought I'd check if it could be adjusted and look at that, already fixed :)

Thanks a lot!
