### ISSUE TITLE
authentication is required by localhost:4000

### ISSUE THREAD

**Issue by kojdigital** [OraOpenSource/apex-frontend-boost#197]
### Issue Description
[Explain]

### APEX Front-End Boost Version
[Example: v2.1.1]

### Operating System
[Example: Windows]

### Node Version
[Example: v4.4.5]

### Browser
[Example: Chrome v50]

### APEX Version
[Example: v5.0.3]

### Web Server
[Example: ORDS 3.0.3, Tomcat 7]

### Your `config.json` file
[Paste code]

**Comment by vincentmorneau** [comment]
I'm sorry but this tells me nothing. Please add a proper description of your problem, screenshots or gifs and also include your environment details. Thanks.

**Comment by kojdigital** [comment]
thanks for your reply , but i have already resolved the issue.
