### ISSUE TITLE
Reorder README.md

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#20]
Need to emphasize what this project does. Look at reordering the main `README.md` file.

**Comment by vincentmorneau** [comment]
README.md is most likely finished for now. How do you want to reorder it?

**Comment by vincentmorneau** [comment]
I find that on the project description, the sourcemaps screenshot and the autoprefixer code snippet are taking too much space compared to the other "main" features. I'm not sure how to fix this.

Feel free to move things around on the README.
