### ISSUE TITLE
Security vulnerability with setting G_APP_IMAGES via URL

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#35]
When app runs, this is launched: `https://localhost:3000/apexdev/f?p=1507:1:::::G_APP_IMAGES:localhost~3000`

A malicious user could then use this knowledge to use a root image folder of their choice for `G_APP_IMAGES`.

Need to re-think about how to set/do this.

**Comment by vincentmorneau** [comment]
Would this be considered a problem in a development environment too?

Tat way we could turn off the application item using a build option, which would secure the prod environment.

**Comment by martindsouza** [comment]
In the development environment not so much.

Yes we could do a BO to get around this but may need to think about it a bit. For example we shouldn't do a BO on `G_APP_IMAGES` as this is the one that the entire application will reference. Perhaps create a temp application with the build option, then modify the application process to set `G_APP_IMAGES = G_TEMP_APP_IMAGES` and this application process also includes a BO.

Overall this process may make things more difficult. A few ideas that come to mind:

- Just use APP_IMAGES
  - On page errors, it wouldn't be set
  - Lose the ability to isolate for multiple devices
- Create a plugin to manage G_APP_IMAGES
  - Not sure how this would look but may be able to code our way around a developer having to create a temp page item and BO.
  - Devs would only need to install the plugin and then create G_APP_IMAGES (again not sure how we'd do this)

**Comment by vincentmorneau** [comment]
This is a very good point. I'm glad you caught it before we release 2.0. 

My thoughts:

* About simply using APP_IMAGES  
  * The ability to use multiple devices is a priority to me on this project. It is the final wow factor for demo purposes and I think it's important we keep it (as an option, not default). 
  * Not being set on error pages could discourage a developer from using 

* About creating a plugin to manage G_APP_IMAGES
  * I don't see how we can get around the BO concern. We need this to be available in dev only. From an APEX development perspective, it's the only way to distinguish environment. Or is it?

Creating a 2nd application item and BO does require more setup, but it feels like the most robust solution to me right now. I'll try it out and see.

**Comment by vincentmorneau** [comment]
@martindsouza, upon preliminary testing it seems that an excluded build option has no effect on an application item...

Will test some more but we may need to think of an alternative.

**Comment by vincentmorneau** [comment]
This commit https://github.com/OraOpenSource/apex-frontend-boost/commit/ce3b23d641bcf211b442fc78b41bc857ae712511 is an attempt to fix the vulnerability issue while keeping all the project's features.

The project's objects dependencies are now:
- 1 build option
- 2 application items
- 2 application processes

They're all very simple, but it's still a lot of objects to create. I'm open to simplification ideas.
