### ISSUE TITLE
Firefox certificate warning (SHA-1)

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-frontend-boost#36]
![image](https://cloud.githubusercontent.com/assets/5391291/12432107/50ae8d7e-bec7-11e5-8087-37ecc9a98bc8.png)

Not sure if we can do anything on our side. Maybe it's a browsersync issue.

**Comment by martindsouza** [comment]
SHA-1 is being deprecated by browsers. We should look in browsersync if there's an option for SHA-2 / SHA-256.

**Comment by vincentmorneau** [comment]
After some research I wasn't able to find anything (I don't know much about certs).

I left an issue on the browsersync repository and will follow it from there: https://github.com/BrowserSync/browser-sync/issues/970

**Comment by martindsouza** [comment]
Created pull request https://github.com/BrowserSync/browser-sync/pull/975

Info: http://itigloo.com/security/generate-an-openssl-certificate-request-with-sha-256-signature/


Overall if this issue isn't fixed on browsersync's end we can't do too much about it.

**Comment by vincentmorneau** [comment]
https://github.com/BrowserSync/browser-sync/pull/975 has been merged. Closing.
