### ISSUE TITLE
JS not auto refreshing

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#50]
When changing a JS file the page doesn't automatically get refreshed. Could be related to #46

**Comment by vincentmorneau** [comment]
What's your console showing?

I'm getting this:
![image](https://cloud.githubusercontent.com/assets/5391291/12627200/8c37a378-c50a-11e5-8bbd-7415c4b64b5a.png)

Also can you copy paste the project config?

**Comment by martindsouza** [comment]
![image](https://cloud.githubusercontent.com/assets/2925726/12627616/17978546-c4fc-11e5-9788-0db67a728e27.png)

The file is stored in multiple sub folders in the `lib` folder. Don't know if that was the problem as I realize most of the time we'll be developing in the `js` folder.

**Comment by vincentmorneau** [comment]
The `lib` folder is not processed for live editing. Only the `js`, `css` and `scss` folders are.

Why do you need to edit a `js` file from `lib`? The idea is that `lib` should be used for 3rd party libraries. 

If you think it should be allowed, I can make browsersync watch `lib` files as well.

**Comment by martindsouza** [comment]
I think it's fine for now. It may become an issue if working on a library that is checked out using something like a git module etc. I'll close this ticket and if we need to watch `lib` we can do when someone needs it (I had minor use case for it).
