### ISSUE TITLE
Public APEX URL

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-frontend-boost#51]
**Using application setup option 2:**
When Browsersync lauches an APEX public URL, the application process set "On New Session" isn't firing, resulting on `G_APP_IMAGES` not being set.

2 solutions come to mind:
- We enforce a random session_id for public apps
- We change the dev application process to launch Before Header, just like option 1

**Comment by martindsouza** [comment]
@vincentmorneau Just changed the docs (see the commit) to run always. Since it's `DEV_ONLY` it won't cause any issues in prod. Close if you're ok with it.

**Comment by vincentmorneau** [comment]
What about public apps in production? Won't the 2nd application process fail as well?

**Comment by martindsouza** [comment]
@vincentmorneau good point. What do you think about changing (or offering 2 processes depending on usage). The process would be the same except for the following:

- When: On load before header...
- Condition: when `G_APP_IMAGES` is null

**Comment by vincentmorneau** [comment]
@martindsouza So the process would be triggered only on the first load. Sounds good to me.

We will need to emphasize on the importance to stick with the documentation.

You can close the issue once `/docs/apex-setup.md` is modified.
