### ISSUE TITLE
Cookie concern

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-frontend-boost#56]
@martindsouza, what if a user no longer wants to use APEX Front-End Boost for his project?

My concern is: the cookie has been set upon browsersync load, but it is never removed or expired. What do you think about it?

BTW I'm laying out the question without proper analysis. Just thinking out loud.

**Comment by martindsouza** [comment]
- [ ] Check that the cookie only resides on the localhost domain (i.e. it's only on `localhost` and not the final domain.

- [ ] Odds are we will just need to look at setting an expiration date.

**Comment by vincentmorneau** [comment]
Personal note: when shutting down gulp, user can no longer use localhost or external IP. Instead goes to it's original app URL, which doesn't use the cookie, so it's all good.

**Comment by martindsouza** [comment]
Only adds a OOS named cookie with localhost so does not affect anything APEX does.

![image](https://cloud.githubusercontent.com/assets/2925726/13970999/5a16b6d6-f052-11e5-814a-ac1597d4135e.png)
