### ISSUE TITLE
Desktop shortcut

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-frontend-boost#60]
@martindsouza, I created a batch file for Windows that makes it much easier to start the project.

Basically by clicking on the shortcut:

![image](https://cloud.githubusercontent.com/assets/5391291/13646681/91cfe844-e5fe-11e5-8564-cd180fec6ea9.png)

The command line opens and asks for the project name:

![image](https://cloud.githubusercontent.com/assets/5391291/13646700/a4d6ab58-e5fe-11e5-80e3-780cc70bbc30.png)

When hitting Enter, the batch file calls for `npm start -- --project=%vProject%`, `vProject` being the previously entered user input.

What do you think? Could it be done for Mac/Linux easily?

**Comment by martindsouza** [comment]
Added OSx/Linux bash script.
