### ISSUE TITLE
Documentation correction for apex-setup.md

### ISSUE THREAD

**Issue by mallkuma** [OraOpenSource/apex-frontend-boost#64]
Small correction under https://github.com/OraOpenSource/apex-frontend-boost/blob/master/docs/apex-setup.md, documentation for "**Option 1) Standard**"  (where images reference the standard APP_IMAGES substitution string)

Currently, it states as "**In Shared Components > Application Items create a new application item with the following attributes:**"

This should read as "**In Shared Components > Application Processes, create a new application process with the following attributes:**"

**Comment by vincentmorneau** [comment]
Nice find, thanks @mallkuma !
