### ISSUE TITLE
npm install error on Node.js v0.10.42: TypeError: Object #<Object> has no method 'access'

### ISSUE THREAD

**Issue by mallkuma** [OraOpenSource/apex-frontend-boost#67]
I have a CentOS 7.2 x64 on which Node.js was installed via OraOpenSource/OXAR. The version of node installed by OXAR is **v0.10.42**.

The generateConfig.js is referencing the File System module to check for existence of config.json. Seems like v0.10.42 does not include the File System module and hence the npm install error.

![npm install error](https://cloud.githubusercontent.com/assets/9077588/14106551/7818f20a-f577-11e5-9467-d13dbfb99f9b.png)

I have no npm install errors on my Windows machine that has Node.js v5.4.1

**Comment by vincentmorneau** [comment]
@martindsouza What's our plan for supporting older Node.js version?

**Comment by martindsouza** [comment]
@vincentmorneau I don't see any issues with only supporting a recent version of Node.js. for this specific issue could we try to include `fs` in the `package.json`. I know it's redundant for current versions of Node.js.

This brings up another idea. Perhaps we create a "System Requirements" or something similar where we list what is required. In this case I think it's pretty simple. APEX 5, Node.js <version>. No need to mention `git` since that's a given.

**Comment by vincentmorneau** [comment]
@martindsouza Agreed for a "System Requirements" section in the README.

Is `git` really a requirement thought? Someone could simply download the repo from github.com

**Comment by martindsouza** [comment]
Agreed, `git` should not be listed.

**Comment by vincentmorneau** [comment]
@mallkuma Are you okay with installing a newer version of Node.js on your CentOs?

**Comment by mallkuma** [comment]
I installed the latest version of Node.js v4.4.1 but I am still getting the same error. So I am guessing it's not the missing module or old version of Node.js but something else. Please see my console below.

<img width="821" alt="npm error 1" src="https://cloud.githubusercontent.com/assets/9077588/14118970/9b55d000-f5b1-11e5-8b44-6aef281c85dd.png">

After npm install, I do a listing of apex-frontend-boost and there is no config.json file.

<img width="345" alt="npm error 2" src="https://cloud.githubusercontent.com/assets/9077588/14119035/e46c073c-f5b1-11e5-981e-e24a114db967.png">

**Comment by mallkuma** [comment]
I was able to resolve this by running npm install with the --unsafe-perm flag as shown below:

<img width="324" alt="npm error 3" src="https://cloud.githubusercontent.com/assets/9077588/14119553/50de9108-f5b4-11e5-9ac3-fe92fd0b1719.png">

[http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd](http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd)

**Comment by vincentmorneau** [comment]
Oh I see, so the `postinstall` script was the issue in Node.js 0.10.42. Good to know.
