### ISSUE TITLE
npm start error: Cannot find module 'through2'

### ISSUE THREAD

**Issue by mallkuma** [OraOpenSource/apex-frontend-boost#69]
On CentOS 7.2, after successful npm install, when I run **apex-frontend-boost.sh**, I get dependency error for module '**through2**.' Please see below console output:

<img width="474" alt="npm start error 1" src="https://cloud.githubusercontent.com/assets/9077588/14121217/29ed447e-f5bc-11e5-9529-859d4f29fe11.png">

I checked package.json and **through2** is not listed as one of the dependencies. However, per error message, /tmp/apex-frontend-boost/lib/scssToLess.js references it.

Listing of node_modules folder does not list through2.
<img width="326" alt="npm start error 2" src="https://cloud.githubusercontent.com/assets/9077588/14121574/bc743f54-f5bd-11e5-90db-78054bd07fd5.png">

As per [https://github.com/robrich/gulp-if/issues/23](https://github.com/robrich/gulp-if/issues/23), I even deleted the entire node_modules folder and re-ran npm install but still the dependency is missing.

I am not sure if I am missing some steps.

**Comment by mallkuma** [comment]
Thanks @vincentmorneau. Worked great after adding **node-fs** and **through2** modules in package.json

<img width="528" alt="npm start success 2" src="https://cloud.githubusercontent.com/assets/9077588/14124509/802ce254-f5cb-11e5-92c0-40e6539f76bc.png">


<img width="318" alt="npm start success" src="https://cloud.githubusercontent.com/assets/9077588/14124446/275b764a-f5cb-11e5-8258-43e38cb03cfa.png">

**Comment by vincentmorneau** [comment]
Great! I don't think we'll add these packages to the main project as we target Node.js 5.x as requirement. 

Thanks again for finding these though, it might help someone else in the future.

**Comment by mallkuma** [comment]
I installed the latest version of Node.js (5.9.1) via nvm and apex-frontend-boost installed and started without any issues.
