### ISSUE TITLE
403 Forbidden message with ORDS 3.0.4 (and possibly 3.0.3 too)

### ISSUE THREAD

**Issue by mallkuma** [OraOpenSource/apex-frontend-boost#70]
Nothing wrong with apex-frontend-boost per se, but thought of just documenting this issue here for users using **apex-frontend-boost with ORDS 3.0.4**

I have a VPS running on CentOS 7.2 on which I had installed ORDS 3.0.4 and APEX using OXAR. I use a Windows local machine with apex-frontend-boost running on it to watch changes to the assets. When I start a Gulp watch, soon after logging into the APEX application, I get **ORDS 403 Forbidden** message as shown below:

![403](https://cloud.githubusercontent.com/assets/9077588/14186904/3f568128-f746-11e5-8a2f-105ce7a0708b.png)

Seems like there is a documented issue [(https://community.oracle.com/message/13659147)](https://community.oracle.com/message/13659147) with static files and ORDS 3.0.3 and 3.0.4. Per Oracle, this issue has been fixed [(ORDS Bugs Fixed 304)](http://www.oracle.com/technetwork/developer-tools/rest-data-services/downloads/ords-bugsfixed-304-2895222.html) in ORDS 3.0.4 but it did not work me.

As a workaround, I had to rebuild the machine from scratch and use **ORDS 3.0.2** instead since OXAR does not come with an uninstall script yet [(OXAR issue # 31).](https://github.com/OraOpenSource/OXAR/issues/31)

**Comment by vincentmorneau** [comment]
@mallkuma Thanks for logging this. Did the error occur only with APEX Front-End Boost, or simply by putting files into the Shared Components - Application Static Files?

I'm trying to see where this belongs in the docs (if it does).

**Comment by tschf** [comment]
I get this 403 whenever doing a POST - minimal set up, pointing config to the app URL and the relevant src and dist folders, with the css, img, js folders set up. 

Even trying to log in to an apex app, I get the 403 forbidden error. Sample `apex.submit` call result below.

From the POST request in the network console (Chrome):

General
```
Request URL:http://localhost:3000/ords/wwv_flow.accept
Request Method:POST
Status Code:403 Forbidden
Remote Address:127.0.0.1:3000
```

Request
```
POST /ords/wwv_flow.accept HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 247
Pragma: no-cache
Cache-Control: no-cache
Origin: http://localhost:3000
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.22 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: http://localhost:3000/ords/f?p=108:LOGIN_DESKTOP:3236195090930:::::
Accept-Encoding: gzip, deflate
Accept-Language: en-AU,en;q=0.8,en-US;q=0.6
Cookie: ORA_WWV_USER_102241778726723=ORA_WWV-myuHxqZ-XPSiZfgZuSbwywha; ORA_WWV_APP_103=ORA_WWV-OnH29Vf4nMdIlMGV6G6GUVdo; ORA_WWV_APP_108=ORA_WWV-BgPgjaNeNMLX4EZER-3x05z7; oos-apex-frontend-boost-app-images=//localhost:3000/; oos-apex-frontend-boost-app-images=//localhost:3000/
```


Response:
```
HTTP/1.1 403 Forbidden
access-control-allow-origin: http://localhost:3000
Set-Cookie: oos-apex-frontend-boost-app-images=//localhost:3000/
server: Apache-Coyote/1.1
error-reason: error="Origin"; error_description*=UTF-8''The%20request%20cannot%20be%20processed%20because%20this%20resource%20does%20not%20support%20Cross%20Origin%20Sharing%20requests%2c%20or%20the%20request%20Origin%20is%20not%20authorized%20to%20access%20this%20resource.%20If%20ords%20is%20being%20reverse%20proxied%20ensure%20the%20front%20end%20server%20is%20propagating%20the%20host%20name%2c%20for%20mod_proxy%20ensure%20ProxyPreserveHost%20is%20set%20to%20On
access-control-allow-credentials: true
vary: Origin
access-control-expose-headers: Error-Reason, Content-Type, Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Credentials, Vary
content-type: text/html
date: Sun, 24 Apr 2016 04:56:34 GMT
connection: close
Transfer-Encoding: chunked
```

Like OP, I'm running 3.0.4

Same page displayed from failed login: 

> The request cannot be processed because this resource does not support Cross Origin Sharing requests, or the request Origin is not authorized to access this resource. If ords is being reverse proxied ensure the front end server is propagating the host name, for mod_proxy ensure ProxyPreserveHost is set to On
Stack trace head:

```
 CORSAccessForbiddenException [statusCode=403, reasons=[The request cannot be processed because this resource does not support Cross Origin Sharing requests, or the request Origin is not authorized to access this resource. If ords is being reverse proxied ensure the front end server is propagating the host name, for mod_proxy ensure ProxyPreserveHost is set to On]]
	at oracle.dbtools.http.cors.CrossOriginRequests.validateRequest(CrossOriginRequests.java:75)
	at oracle.dbtools.http.entrypoint.Dispatcher.validateCorsPolicy(Dispatcher.java:232)
	at oracle.dbtools.http.entrypoint.Dispatcher.dispatch(Dispatcher.java:108)
	at oracle.dbtools.http.entrypoint.EntryPoint$FilteredServlet.service(EntryPoint.java:153)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:73)
```

Let me know if you need any other info?

**Comment by tschf** [comment]
Further to my last comment, this was by testing in Chrome (version 51 and 52; Linux and Windows respectively.)

Interestingly, I notice that the `Access-Control-Allow-Origin: *` header doesn't seem to make it to the response header in Chrome (on POSTs, seemingly reverting to `access-control-allow-origin: http://localhost:3000`), whereas it's as expected in Firefox.

![image](https://cloud.githubusercontent.com/assets/1747643/14765929/4acd7e8c-0a3b-11e6-9b04-782cee69e3c2.png)

(Tested in both Firefox (Ubuntu) and IE - both work fine).

**Comment by vincentmorneau** [comment]
Thanks to you both, I'll definitely take a closer look this week.

**Comment by vincentmorneau** [comment]
I have received another bug report about this. Need to make it top priority.

@martindsouza if you have any idea let me know.

**Comment by martindsouza** [comment]
@tschf Are you getting the same POST issue in FF?

@vincentmorneau No ideas right now but can look into more detail next week.

**Comment by tschf** [comment]
@martindsouza No, Firefox works good

**Comment by tschf** [comment]
Is there a scenario where you've needed to set that `Access-Control-Allow-Origin-Header`.?

```js
res.setHeader('Access-Control-Allow-Origin', '*');
```

If I comment it out, it works fine for me in all browsers.

But unsure on the reasoning for adding it in - maybe it was needed for some cases? 
I also tried using a value of `null`, and it too worked in Chrome - although, still seemed to be ignored when inspecting the network console. Odd.

**Comment by vincentmorneau** [comment]
That's a very good point. To be honest adding `res.setHeader('Access-Control-Allow-Origin', '*');` did fix _something_ in the past related to an icon library served via a CDN (as part of material design icons in https://apex.oracle.com/pls/apex/f?p=12192). 

I just tried again today without the middleware and it's working fine as well. I'll make some more testing but this definitely seems like a good thing to remove (never really liked it).

Thanks again @tschf, you're saving me a lot of research time!

**Comment by vincentmorneau** [comment]
Couldn't reproduce my icon issue, even without `res.setHeader('Access-Control-Allow-Origin', '*');`, so I'm officially removing it for v2.1

**Comment by martindsouza** [comment]
@vincentmorneau Since this is such a critical bug (i.e doesn't work for Chrome Devs) can we port this patch to a 2.0.1 bug fix?

**Comment by vincentmorneau** [comment]
@martindsouza Actually 2.1.0 is one (minor) issue short from being complete. I intend to publish it in the next couple of days.
