### ISSUE TITLE
Missing dependency through2

### ISSUE THREAD

**Issue by fuzziebrain** [OraOpenSource/apex-frontend-boost#73]
Got an error when launching AFB, post npm install. The module `through2 `is missing from the list of dependencies.

**Comment by vincentmorneau** [comment]
Thanks! I believe Node.js 4+ has through2 built in. Or maybe not, but I never had to install it myself. Nevertheless I'll add it for compatibility at least. Still undecided about `"through2": "^2.0.1"` vs `"through2": "2.0.x"`. What do you think?
