### ISSUE TITLE
Package.json dependencies syntax

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-frontend-boost#75]
@martindsouza Before I accept @fuzziebrain PR, I need to ask, do you usually write your dependencies like this: `"through2": "^2.0.1"`

or like that: `"through2": "2.0.x"`

Read https://docs.npmjs.com/files/package.json#dependencies for explanation.

I tend to use `"2.0.x"` simply because it gives more control to the developer, but I'd like to hear your opinion.

**Comment by martindsouza** [comment]
@vincentmorneau I'm still fairly new to dependencies. Usually when I add them I have `npm` automatically add them through the `--S` parameter.

Overall I like your idea of `2.0.x` Since it'll keep the same version but just update to the latest patch set good with me.
