### ISSUE TITLE
error in gulp package

### ISSUE THREAD

**Issue by omarsawalhah** [OraOpenSource/apex-frontend-boost#76]
I have installed nodeJS using brew installer and had problems when starting.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "start" "--" "--project=demo"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! apex-frontend-boost@2.0.0 start: `gulp "--project=demo"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apex-frontend-boost@2.0.0 start script 'gulp "--project=demo"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apex-frontend-boost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp "--project=demo"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apex-frontend-boost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apex-frontend-boost
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

I also tried to install gulp with the following command
npm install -g gulp

but didn't work.

**Comment by martindsouza** [comment]
@omarsawalhah did you do a `npm install` on the project before running the `npm start`?

**Comment by omarsawalhah** [comment]
Thanks martin, 
I just figured out the problem was I didn’t run “npm install”, I have already done this and I am able to start it.
Many thanks.

Regards,
---
Omar Sawalhah
CTO 
More for Advanced Solutions
omar@mas-jo.com
omarsawalhah@yahoo.com
www.mas-jo.com
+962 795 21 77 55

**Comment by martindsouza** [comment]
@omarsawalhah No problem. I'll close this ticket. The install also installed Gulp (just mentioned since you had said that you installed Gulp manually).
