### ISSUE TITLE
Error while trying to run it on Win10

### ISSUE THREAD

**Issue by lschilde** [OraOpenSource/apex-frontend-boost#81]
Hi team, 

just a quick info that I had issues running on Win 10. 

For some reason it does not like when I start running the script to create project. This is what I got in log:

>...\Apex-frontend-boost\apex-frontend-boost>npm start -- --project=linotest

> apex-frontend-boost@2.0.0 start E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost\apex-frontend-boost
> gulp "--project=linotest"

'gulp' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--project=linotest"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! apex-frontend-boost@2.0.0 start: `gulp "--project=linotest"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apex-frontend-boost@2.0.0 start script 'gulp "--project=linotest"'.
npm ERR! This is most likely a problem with the apex-frontend-boost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp "--project=linotest"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apex-frontend-boost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls apex-frontend-boost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost\apex-frontend-boost\npm-debug.log

/************************************************************************/

this was my install log:
-- installing from github
E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost>npm install
npm WARN enoent ENOENT: no such file or directory, open 'E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost\package.json'
npm WARN Apex-frontend-boost No description
npm WARN Apex-frontend-boost No repository field.
npm WARN Apex-frontend-boost No README data
npm WARN Apex-frontend-boost No license field.

so seemed to me to be fine. Is there something I am doing wrong or?
I am running node vs 4. Please let me know if you need more info. 

Thanks,
Lino

**Comment by vincentmorneau** [comment]
Hi Lino,

Have you executed `npm install` prior to `npm start -- --project=linotest`. This will install all the dependencies, and will also generate a `config.json` in which you will need to add your `linotest` project. Make it look like this:

```json
{
    "linotest": {
        "appURL": "yourApplicationURL",
        "srcFolder": "yourLocalSrcFolder",
        "distFolder": "yourLocalDistFolder"
    }
}
```

Does it help?

**Comment by lschilde** [comment]
Hi Vincent,

thanks for coming back on this.

yes I did run:
 npm install

this is what I got:
E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost>npm install
npm WARN enoent ENOENT: no such file or directory, open
'E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost\package.json'
npm WARN Apex-frontend-boost No description
npm WARN Apex-frontend-boost No repository field.
npm WARN Apex-frontend-boost No README data
npm WARN Apex-frontend-boost No license field.


E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost>dir
 Volume in drive E is LS-60GB

 Directory of E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost

25/04/2016  10:06 AM    <DIR>          .
25/04/2016  10:06 AM    <DIR>          ..
25/04/2016  10:06 AM    <DIR>          apex-frontend-boost
25/04/2016  10:06 AM    <DIR>          node_modules
               0 File(s)              0 bytes
               4 Dir(s)  12,725,002,240 bytes free


But in my apex-frontend-boost there was no config.json to edit before
running npm start command.
Maybe this is the problem.

This is content of my apex-frontend-boost after install run:
 Directory of
E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost\apex-frontend-boost

25/04/2016  11:18 AM    <DIR>          .
25/04/2016  11:18 AM    <DIR>          ..
25/04/2016  10:06 AM               395 .gitattributes
25/04/2016  10:06 AM                49 .gitignore
25/04/2016  10:06 AM                49 .travis.yml
25/04/2016  10:06 AM               125 apex-frontend-boost.bat
25/04/2016  10:06 AM            99,678 apex-frontend-boost.ico
25/04/2016  10:06 AM             3,360 apex-frontend-boost.lnk
25/04/2016  10:06 AM               949 apex-frontend-boost.sh
25/04/2016  10:06 AM               469 changelog.md
25/04/2016  10:06 AM               750 default.json
25/04/2016  10:06 AM    <DIR>          docs
25/04/2016  10:06 AM               598 generateConfig.js
25/04/2016  10:06 AM             9,915 gulpfile.js
25/04/2016  10:06 AM    <DIR>          lib
25/04/2016  10:06 AM             1,101 LICENSE
25/04/2016  10:41 AM             2,658 Lino_errors.txt
25/04/2016  10:06 AM    <DIR>          media
25/04/2016  11:17 AM    <DIR>          node_modules
25/04/2016  11:17 AM             1,236 package.json
25/04/2016  10:06 AM             4,115 README.md
              15 File(s)        125,447 bytes
               6 Dir(s)  12,722,065,408 bytes free

E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost\apex-frontend-boost>


Thanks,
Lino

**Comment by vincentmorneau** [comment]
Hi @lschilde,

It appears like you haven't cloned apex-frontend-boost into `E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost`.

If you use Git, you can simply do
```bash
git clone https://github.com/OraOpenSource/apex-frontend-boost.git
cd apex-frontend-boost
npm install
```

Otherwise you can download the project off Github directly by clicking [here](https://github.com/OraOpenSource/apex-frontend-boost/archive/master.zip) and then extracting the content to `E:\2016-WORK\LS-APEX2016\APEX_RnD\Apex-frontend-boost` and then you can do `npm install`.

Does that make sense? Let me know.

**Comment by lschilde** [comment]
Hi Vincent,

I got to what the problem was.

First time I did clone from git I had node 5 version installed and for some
reason it has not copied all files.
So all my next steps did not run properly.

Now I got it working perfectly fine. I deleted my original folder, got node
4 and followed config steps. They all worked now.

Appreciate all the help,
Lino

**Comment by vincentmorneau** [comment]
Perfect! Closing the issue now.
