### ISSUE TITLE
Rebind BrowserSync remote debug port

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/apex-frontend-boost#83]
After starting the service, one of the URLS:

```
UI: http://localhost:3001
```

Which seems like a web interface to BrowserSync. 

One such feature is remote debug.

According to http://wearejh.com/news/browsersync-2-0/:

> The UI includes the weinre project that enables remote debugging on connected devices. Think ‘inspect element’ – but not limited to dev tools. Along with weinre, our Remote Debug section also includes some simpler tools that we’ve found to be especially useful when working with multiple devices.

In the web interface, we have:

![image](https://cloud.githubusercontent.com/assets/1747643/14849078/5c8454cc-0cb4-11e6-87e9-4fe33eab9cab.png)

When switching `Remote Debugger (weinre)` on I get this error page:

![image](https://cloud.githubusercontent.com/assets/1747643/14849126/8e6935f2-0cb4-11e6-9093-6825535a8724.png)

With the following console output:

```
2016-04-27T10:13:38.701Z gulp: error running server: Error: listen EADDRINUSE 192.168.0.146:8080
```

Alas, port 8080 is already bound on localhost.

**Comment by vincentmorneau** [comment]
@tschf Could this be a Browsersync bug?

**Comment by tschf** [comment]
On the docs, it specifies options, where you can specify ports in the `ui` object.

See: https://www.browsersync.io/docs/options/

```js
// Change the default weinre port
ui: {
    port: 8080,
    weinre: {
        port: 9090
    }
}
```

I guess you could pick a port, then check if it's bound? Not sure of the best approach here. The served ports for both UI and the app seem to handle bound ports quite well, unlike the weinre port.

**Comment by vincentmorneau** [comment]
@tschf I'll add a `ui-port` variable available to use in APEX Front-End Boost `config.json`, defaulted to 8080, but changeable per project.
