### ISSUE TITLE
Auto Upload Files

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#84]
Auto upload the files to the application static files (could be an option or another command, still need to think of it)
- [ ] `wwv_flow_api.create_app_static_file` will create or update the file based on id/filename
  - In theory this can be done in current versions of APEX. It'll leave old files around but we can clean them up manually every so often.
  - See application export file for example. For the base64 array keep the string length the same as they're some issues with going beyond this length.
- [ ] `wwv_flow_api.delete_app_static_file` (only available in 5.1) will allow us to delete application static files. Since it's 5.1 only will need to put some conditional compilation.

**Comment by vincentmorneau** [comment]
Do you think it would be useful to have the dist folder zipped automatically? Or this auto upload would make the zip obsolete?

**Comment by martindsouza** [comment]
@vincentmorneau The zip will be required for auto upload. Essentially we'll delete all the files from the APEX Static Files, then upload the zip from CLI.

**Comment by vincentmorneau** [comment]
@martindsouza Do you want me to take this one off your plate?

I think now that EA1 is out we can start developing this feature in a separate branch.

**Comment by martindsouza** [comment]
@vincentmorneau Sure. I'll keep my name on it as an interested party but if you want to work on it that would be great.

**Comment by vincentmorneau** [comment]
Just leaving a note here: Lots of the questions I received at Kscope16 was concerning the final upload process. There is a lot of interest for this feature.

**Comment by vincentmorneau** [comment]
@martindsouza Are you thinking of including `node-oracledb` as a package dependency here? I don't see how we would call the APIs otherwise.

I'm asking because the installation of `node-oracledb` itself is a bit cumbersome (lots of requirements) and I know we would end up doing more support over the installation itself. What do you think?

**Comment by vincentmorneau** [comment]
Follow-up: will be using sqlcl instead for lighter dependencies.
