### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#90]
From https://github.com/blog/2111-issue-and-pull-request-templates

Things we could ask for:

- [ ] Version of Node (and example to find it)
- [ ] Config file???

**Comment by vincentmorneau** [comment]
Ended up with these
- [ ] Issue Description
- [ ] APEX Front-End Boost Version
- [ ] Operating System
- [ ] Node Version
- [ ] Browser
- [ ] APEX Version
- [ ] Web Server
