### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by hg-smart** [OraOpenSource/apex-frontend-boost#92]
Hello Vincent,

very nice youtube video about apex frontend boost.

What do we actually need when we developed a application using apex frontend boost application and want to deploy it on a prod or qa server. 

Upload app.min.css and js in shared components ? Is there any possibilty to automate this ?

Best
Hansjörg

**Comment by vincentmorneau** [comment]
Hi Hansjörg,

We have plans to automate this in the future.

Today, you would have to zip the `/dist/` folder et upload it to APEX Shared Components - Application Static Files. In your Prod or QA server, APEX Front-End Boost wouldn't be running so your app will redirect to #APP_IMAGES# correctly, as usual.

Does that make sense to you? Let me know.

**Comment by martindsouza** [comment]
@hg-smart Starting in APEX 5.1 we'll be able to add the functionality to auto upload the `dist` folder back into the application's static files. See #84 for more details.

**Comment by hg-smart** [comment]
perfect for me.
