### ISSUE TITLE
Install instructions are not correct

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#93]
`npm install apex-frontend-boost` is not the correct way to install project. If you do that it installs everyting in `~/node_modules`

**Comment by vincentmorneau** [comment]
I'm not too familiar with Unix, but `~/` is the root of what exactly? For me, `npm install apex-frontend-boost` creates `node_modules` into the active directory, and installs all the dependencies there.

Another thought: we could suggest `npm install -g apex-frontend-boost` which installs it globally. One caveat is it makes finding config.json more complicated and less intuitive (Example: `C:\Users\vince\AppData\Roaming\npm\node_modules\apex-frontend-boost\config.json`). I'll keep this thought on hold for now.

Based on https://github.com/npm/npm/issues/3597, I am not against reverting back to `git clone`, but I would keep npm as well as another option. I'll actually document both options, but will have `git clone` first.
